# Generated by Django 4.1.3 on 2022-11-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiler_topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoilertopic',
            name='netflix_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spoilertopic',
            name='no_vote',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spoilertopic',
            name='yes_vote',
            field=models.IntegerField(null=True),
        ),
    ]
