# Generated by Django 4.1.3 on 2022-11-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiler_topics', '0003_spoilertopic_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoilertopic',
            name='netflix_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spoilertopic',
            name='no_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spoilertopic',
            name='topic_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spoilertopic',
            name='yes_vote',
            field=models.IntegerField(default=0),
        ),
    ]
