# Generated by Django 4.1.3 on 2022-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiler_topics', '0004_alter_spoilertopic_netflix_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoilertopic',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
